require: rubocop-rails

Rails/HasAndBelongsToMany:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal

